version: '3.7'

services:

  nodered:
    image: sheng2216/nodered-docker:modbus
#    build:
#      context: ./node-red-bacnet-edition
#      dockerfile: ./Dockerfile
    container_name: NodeRed
    user: node-red
    group_add:
      - "997"
      - "998"
      - dialout
    restart: unless-stopped
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    volumes:
      - './volume/node-red/data:/data'
    ports:
      - "1880:1880"
    entrypoint: /data/entrypoint.sh
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - NODE_RED_ENABLE_PROJECTS=${NODE_RED_ENABLE_PROJECTS:-false}
    depends_on:
      - influxdb
    network_mode: "host"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb 
    restart: unless-stopped
    ports:
      - '8086:8086'
    networks:
      - bridge
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=changeme

  grafana:
    image: grafana/grafana:latest
    container_name: grafana 
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - bridge
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./volume/grafana/provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme

volumes:
  node-red-data:
  influxdb-storage:
  grafana-storage:

networks:
  bridge:
