apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy 
    database: sensors 
    orgId: 1
    user: admin
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: changeme 
    version: 1
    editable: false
    isDefault: true
